[package]
name = "calcagebra"
version = "1.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
rustyline = "14.0.0"
textplots = "0.8.6"

[profile.release]
strip = true
opt-level = "z"

[profile.dev]
opt-level = 3
debug = true
